#! /bin/bash

library=specmap
version="$(cat src/${library}.dart | grep 'VERSION = ' | sed 's/.*VERSION = "\(.*\)".*/\1/g')"
package="pkg/$library.dart"

echo "Packaging $version of $library"
mkdir -pv pkg
rm -fv "$package"
for file in `find src -iname '*.dart'`; do
  # cat the file without comments or empty lines or #sources into the package
  cat "$file" | grep -v -e '^[ ]*\/\/' | grep -v -e '^[ ]*$' | grep -v '#source(' >> "$package"
done
echo "Done.  Created $package"
